services:
  - type: web
    name: qr-cafe
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: APP_ENV
        value: production
      - key: FLASK_CONFIG
        value: production
      - key: SOCKETIO_ASYNC_MODE
        value: eventlet
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: qr-cafe-db
          property: connectionString

databases:
  - name: qr-cafe-db
    databaseName: qrcafe
    user: qrcafe
