services:
  - type: web
    name: qr-cafe
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask --app run.py init-db && flask --app run.py seed-data && gunicorn --bind 0.0.0.0:$PORT --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: APP_ENV
        value: production
      - key: FLASK_CONFIG
        value: production
      - key: SOCKETIO_ASYNC_MODE
        value: eventlet
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: DATABASE_URL
        fromDatabase:
          name: qr-cafe-db
          property: connectionString

databases:
  - name: qr-cafe-db
    databaseName: qrcafe
    user: qrcafe
